gateways:
  postgres:
    connection:
      type: postgres
      host: {{ env_var('POSTGRES_HOST') }}
      port: 5432
      user: {{ env_var('POSTGRES_USER') }}
      password: {{ env_var('POSTGRES_PASSWORD') }}
      database: demo
    state_connection:
      type: postgres
      host: {{ env_var('POSTGRES_HOST') }}
      port: 5432
      user: {{ env_var('POSTGRES_USER') }}
      password: {{ env_var('POSTGRES_PASSWORD') }}
      database: sqlmesh_state

default_gateway: postgres

model_defaults:
  dialect: postgres
  start: 2024-12-16
