gateways:
  postgres:
    connection:
      type: postgres
      host: {{ env_var('POSTGRES_HOST') }}
      port: 5432
      user: {{ env_var('POSTGRES_USER') }}
      password: {{ env_var('POSTGRES_PASSWORD') }}
      database: demo
    state_connection:
      type: postgres
      host: {{ env_var('POSTGRES_HOST') }}
      port: 5432
      user: {{ env_var('POSTGRES_USER') }}
      password: {{ env_var('POSTGRES_PASSWORD') }}
      database: sqlmesh_state
  duckdb:
    connection:
      type: duckdb
      catalogs:
        demo:
          type: postgres
          path: 'dbname=demo user={{ env_var("POSTGRES_USER") }} host={{ env_var("POSTGRES_HOST") }} password={{ env_var("POSTGRES_PASSWORD") }}'
      # extensions:
      #   - name: iceberg
      #   - name: httpfs
      # connector_config:
      #   s3_access_key_id: {{ env_var('AWS_ACCESS_KEY_ID') }}
      #   s3_secret_access_key: {{ env_var('AWS_SECRET_ACCESS_KEY') }}

default_gateway: postgres

model_defaults:
  dialect: postgres
  start: 2024-12-16
