gateways:
  postgres:
    connection:
      type: postgres
      host: {{ env_var('POSTGRES_HOST') }}
      port: 5432
      user: {{ env_var('POSTGRES_USER') }}
      password: {{ env_var('POSTGRES_PASSWORD') }}
      database: demo
    state_connection:
      type: postgres
      host: {{ env_var('POSTGRES_HOST') }}
      port: 5432
      user: {{ env_var('POSTGRES_USER') }}
      password: {{ env_var('POSTGRES_PASSWORD') }}
      database: sqlmesh_state
  duckdb:
    connection:
      type: duckdb
      catalogs:
        demo:
          type: postgres
          path: 'dbname=demo user=myuser host=localhost'
      extensions:
        - name: iceberg
        - name: httpfs

default_gateway: postgres

model_defaults:
  dialect: postgres
  start: 2024-12-16
