[project]
name = "multi-engine-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyarrow>=18.1.0",
    "pyiceberg[glue]>=0.8.1",
    "ruff>=0.8.3",
    "sqlmesh[postgres,web]>=0.140.1",
]
